#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###########################################################################
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
###########################################################################
# #
# # PRELUDE - Standard startup code for loading mulle-bashfunctions
# #
###

#
# Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
#
if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
then
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
   export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
fi

#
# The booter reruns the executable either with bash or zsh, whatever the
# system provides. On the second run --no-auto-shell will be set first.
#
if [ "$1" != --no-auto-shell ]
then
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
else
   shift    # get rid of --no-auto-shell
fi


#
# Include mulle-bashfunctions.sh         : default functions
#         mulle-bashfunctions-none.sh    : almost no functions
#         mulle-bashfunctions-minimal.sh : few functions for basic scripts
#         mulle-bashfunctions-all.sh     : everything, even obscure functions
#
# Do this first to get aliases
#
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

###
# # Now we are in bash or zsh with mulle-bashfunctions loaded
# #
###########################################################################
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
###########################################################################


filter_darwin()
{
   sed -e 's|/Applications/Xcode.*\.app/.*/MacOSX.*\.sdk|\${SDKPATH}|g' |
   sed -e 's|/Library/Developer/CommandLineTools/SDKs/MacOSX.*\.sdk|\${SDKPATH}|g'
}


emit_args()
{
   local argument
   local key
   local value
   local envvar
   local prefix
   local subst

   prefix="`eval "echo \$MOCK_TEST_DIR"`"
   r_escaped_sed_pattern "${prefix}"
   prefix="${RVAL}"

   while [ "$#" -ne 0 ]
   do
      argument="$1"
      case "${argument}" in
         -project|-target|-configuration|-scheme|-workspace|-sdk|-destination*)
            shift
            printf "%s %s\n" "${argument}" "$1"
         ;;

         -xc*|-export-*|-arch|-enable*|-*Path|-*Language|-toolchain)
            shift
            printf "%s %s\n" "${argument}" "$1"
         ;;

         -*=*)
            key="$(cut -d= -f1 <<< "${argument:1}")"
            value="$(cut -d= -f2- <<< "${argument:1}")"
            subst="$(sed "s/^\\(.*\\)${prefix}\\(.*\\)/\\1\${MOCK_TEST_DIR}\\2/g" <<< "${value}")"
            subst="$(sed "s|^/private\${MOCK_TEST_DIR}|\${MOCK_TEST_DIR}|" <<< "${subst}")"
            printf "%s\n" "<$key=${subst}>"
         ;;

         *=*)
            key="$(cut -d= -f1 <<< "${argument}")"
            value="$(cut -d= -f2- <<< "${argument}")"
            subst="$(sed "s/^\\(.*\\)${prefix}\\(.*\\)/\\1\${MOCK_TEST_DIR}\\2/g" <<< "${value}")"
            subst="$(sed "s|^/private\${MOCK_TEST_DIR}|\${MOCK_TEST_DIR}|" <<< "${subst}")"
            printf "%s\n" "$key=${subst}"
         ;;

         # commands ignore
         -license|-usage|-version|-showsdks|-showBuildSettings|-list|-exportArchive|-exportLocalizations|-importLocalizations)
         ;;

         # actions ignore
         build|build-for-testing|analyze|archive|test|test-without-building|install-src|install|clean)
         ;;

         "")
         ;;

         *)
            printf "%s\n" "${argument}"
         ;;
      esac

      shift
   done
}


main()
{
   local envvar
   local filename

   envvar="`basename -- "$0" | sed 's/^[A-Za-z]*-\(.*\)/\1/' | tr '[a-z]' '[A-Z]'`_REDIRECT_FILE"
   if [ ! -z "${ZSH_VERSION}" ]
   then
      filename="${(P)envvar}"
   else
      filename="${!envvar}"
   fi
   if [ ! -z "${filename}"  ]
   then
      log_info "${MULLE_EXECUTABLE_NAME}: Writing defines to \"${filename}\""
      emit_args "$@" | filter_darwin | LC_ALL=C sort > "${filename}"
   else
      emit_args "$@" | filter_darwin | LC_ALL=C sort
   fi
}


main "$@"


