#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###########################################################################
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
###########################################################################
# #
# # PRELUDE - Standard startup code for loading mulle-bashfunctions
# #
###

#
# Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
#
if ! [ ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR+x} ]
then
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
   export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
fi

#
# The booter reruns the executable either with bash or zsh, whatever the
# system provides. On the second run --no-auto-shell will be set first.
#
if [ "${1:-}" != --no-auto-shell ]
then
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
else
   shift    # get rid of --no-auto-shell
fi


#
# Include mulle-bashfunctions.sh         : default functions
#         mulle-bashfunctions-none.sh    : almost no functions
#         mulle-bashfunctions-minimal.sh : few functions for basic scripts
#         mulle-bashfunctions-all.sh     : everything, even obscure functions
#
# Do this first to get aliases
#
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

###
# # Now we are in bash or zsh with mulle-bashfunctions loaded
# #
###########################################################################
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
###########################################################################


filter_darwin()
{
   sed -e 's|/Applications/Xcode.*\.app/.*/MacOSX.*\.sdk|\${SDKPATH}|g' |
   sed -e 's|/Library/Developer/CommandLineTools/SDKs/MacOSX.*\.sdk|\${SDKPATH}|g'
}


emit_args()
{
   local key

   while [ "$#" -ne 0 ]
   do
      key="$1"
      case "${key}" in
         -*=*)
            printf "%s\n" "${key}"
         ;;

         --backend|--prefix)
            shift
            printf "%s\n" "${key} `basename -- "$1"`"
         ;;

         --buildtype|--*dir)
            shift
            printf "%s\n" "${key} $1"
         ;;

         -*)
            printf "%s\n" "${key}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   while [ "$#" -ne 0 ]
   do
      # just emit directory names
      basename -- "$1"
      shift
   done
}


emit_env()
{
   local key
   local value

   IFS=':'
   shell_disable_glob
   for key in ${__MULLE_MAKE_ENV_ARGS}
   do
      shell_enable_glob
      if [ ! -z "${key}" ]
      then
         if [ ${ZSH_VERSION+x} ]
         then
            value="${(P)key}"
         else
            value="${!key}"
         fi
         echo "[${key}=${value}]"
      fi
   done
   IFS="${DEFAULTIFS}"
   shell_enable_glob
}


emit_env_and_args()
{
   emit_env
   emit_args "$@"
}


main()
{
   local envvar
   local filename

   [ -z "${__MULLE_MAKE_ENV_ARGS}" ] &&
      fail "not called by mulle-make (__MULLE_MAKE_ENV_ARGS is missing)"

   envvar="`basename -- "$0" | sed 's/^[A-Za-z]*-\(.*\)/\1/' | tr '[a-z]' '[A-Z]'`_REDIRECT_FILE"
   if [ ${ZSH_VERSION+x} ]
   then
      filename="${(P)envvar}"
   else
      filename="${!envvar}"
   fi
   if [ ! -z "${filename}"  ]
   then
      log_info "${MULLE_EXECUTABLE_NAME}: Writing defines to \"${filename}\""
      emit_env_and_args "$@" | filter_darwin | LC_ALL=C sort > "${filename}"
   else
      emit_env_and_args "$@" | filter_darwin | LC_ALL=C sort
   fi
}


main "$@"
