#! /usr/bin/env bash
#
#   Copyright (c) 2015-2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
if [ "${TRACE}" = "YES" ]
then
   set -x
fi

MULLE_EXECUTABLE_VERSION_MAJOR=0
MULLE_EXECUTABLE_VERSION_MINOR=2
MULLE_EXECUTABLE_VERSION_PATCH=0

MULLE_EXECUTABLE_VERSION="${MULLE_EXECUTABLE_VERSION_MAJOR}.${MULLE_EXECUTABLE_VERSION_MINOR}.${MULLE_EXECUTABLE_VERSION_PATCH}"


MULLE_EXECUTABLE_BASHFUNCTIONS="1"


#
# This is the main user interface to mulle-make
# sorta like git
#

trap_fail()
{
   exit 1
}


SHOWN_COMMANDS="\
   build         : build project [default]
   log           : show build log
   install       : build project and install
   version       : print mulle-make version"


HIDDEN_COMMANDS="\
   libexec-path  : print path to ${MULLE_EXECUTABLE_NAME} libexec
   uname         : ${MULLE_EXECUTABLE_NAME}'s simplified uname(1)"


print_commands()
{
   local  show_all="${1:-NO}"

   echo "${SHOWN_COMMANDS}"

   if [ "${show_all}" != "NO" ]
   then
      echo "${HIDDEN_COMMANDS}"
   fi
}


print_flags()
{
   cat <<EOF
   -f            : force operation
   -V            : verbose make
   --args <file> : read the commandline from <file>. Must be only option.
EOF

   options_technical_flags_usage "         : "
}


usage()
{
   local verbose="${1:-NO}"

   cat <<EOF
Usage:
   ${MULLE_EXECUTABLE_NAME} [flags] [command] [options]

   Build a project using cmake or configure or something else.

Flags:
EOF

   print_flags | sort

   cat <<EOF

Commands:
EOF

   print_commands "${verbose}"

   if [ "${verbose}" = "NO" ]
   then
      cat <<EOF
      (use mulle-make -v help to show more commands)
EOF
   fi

   cat <<EOF

Options are command specific. Use ${MULLE_EXECUTABLE_NAME} <command> -h for help.
EOF

   exit 1
}


#
# stolen from:
# http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
# ----
#
_prepend_path_if_relative()
{
   case "$2" in
      /*)
         echo "$2"
      ;;
      *)
         echo "$1/$2"
      ;;
   esac
}


resolve_symlinks()
{
   local dir_context
   local linkpath

   if linkpath="`readlink "$1"`"
   then
      dir_context=`dirname -- "$1"`
      resolve_symlinks "`_prepend_path_if_relative "${dir_context}" "${linkpath}"`"
   else
      echo "$1"
   fi
}


fetch_libexec_path()
{
   local executablepath="$1"

   local exedir
   local exedirpath
   local prefix
   local libexecpath

   case "${executablepath}" in
      \.*|/*|~*)
      ;;

      *)
         executablepath="`command -v "${executablepath}"`"
      ;;
   esac

   executablepath="`resolve_symlinks "${executablepath}"`"
   exedirpath="`dirname "${executablepath}"`"
   prefix="`dirname "${exedirpath}"`"
   libexecpath="${prefix}/libexec/mulle-make"

   if [ ! -x "${libexecpath}/mulle-make-build.sh" ]
   then
      libexecpath="${exedirpath}/src"
   fi

   case "$libexecpath" in
      /*|~*)
      ;;

      *)
         libexecpath="$PWD/$libexecpath"
      ;;
   esac

   if [ -x "${libexecpath}/mulle-make-build.sh" ]
   then
      echo "${libexecpath}"
   fi
}


_main()
{
   local MULLE_FLAG_MAGNUM_FORCE="NONE"
   local MULLE_FLAG_IGNORE_GRAVEYARD="NO"

   # technical flags
   local MULLE_FLAG_EXEKUTOR_DRY_RUN="NO"
   local MULLE_FLAG_LOG_LOCAL="NO"
   local MULLE_FLAG_LOG_DEBUG="NO"
   local MULLE_FLAG_LOG_EXEKUTOR="NO"
   local MULLE_FLAG_LOG_FLUFF="NO"
   local MULLE_FLAG_LOG_SCRIPTS="NO"
   local MULLE_FLAG_LOG_SETTINGS="NO"
   local MULLE_FLAG_LOG_VERBOSE="NO"
   local MULLE_FLAG_LOG_MERGE="NO"
   local MULLE_TRACE_POSTPONE="NO"
   local MULLE_FLAG_VERBOSE_MAKE="NO"

   #
   # simple option handling
   #
   local argument

   while read -r argument
   do
      if options_technical_flags "${argument}"
      then
         continue
      fi

      case "${argument}" in
         -f|--force)
            MULLE_FLAG_MAGNUM_FORCE="BOTH"
         ;;

         -h|--help)
            usage "${MULLE_TRACE}"
         ;;

         -V|--verbose-make)
            MULLE_FLAG_VERBOSE_MAKE="YES"
         ;;

         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            log_error "Unknown flag \"${argument}\""
            usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

   done

   options_setup_trace "${MULLE_TRACE}"

   local cmd

   cmd="${argument:-make}"

   MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME} ${cmd}"
   MULLE_EXECUTABLE_OPTIONS="$@"

   case "${cmd}" in
      build|make)
         # shellcheck source=src/mulle-make-build.sh
         . "${MULLE_MAKE_LIBEXEC_DIR}/mulle-make-build.sh"

         make_build_main "$@"
      ;;

      install)
         # shellcheck source=src/mulle-make-build.sh
         . "${MULLE_MAKE_LIBEXEC_DIR}/mulle-make-build.sh"

         make_install_main "$@"
      ;;

      list|plugins)
         # shellcheck source=src/mulle-make-systeminstall.sh
         . "${MULLE_MAKE_LIBEXEC_DIR}/mulle-make-list.sh"

         make_list_main "$@"
      ;;

      help)
         usage "${MULLE_TRACE}"
      ;;

      libexec-path|library-path)
         echo "${MULLE_MAKE_LIBEXEC_DIR}"
      ;;

      uname)
         echo "${UNAME}"
      ;;

      version)
         echo "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      *)
         log_error "Unknown command \"${cmd}\""
         usage "${MULLE_TRACE}"
      ;;
   esac
}


_init()
{
   #
   # minimal setup exit
   #
   if [ "$1" = "version" ]
   then
      echo "${MULLE_EXECUTABLE_VERSION}"
      exit 0
   fi

   MULLE_MAKE_LIBEXEC_DIR="`fetch_libexec_path "$0"`"
   if [ -z "${MULLE_MAKE_LIBEXEC_DIR}" ]
   then
      echo "$0 fatal error: Could not find libexec ($PWD)" >&2
      exit 1
   fi

   #
   # minimal setup exit
   #
   case "$1" in
      "libexec-path"|"library-path")
         echo "${MULLE_MAKE_LIBEXEC_DIR}"
         exit 0
      ;;
   esac

   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-path 2> /dev/null`"
   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      if [ -z "`command -v "${executablepath}"`" ]
      then
          echo "$0 fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
      else
         echo "$0 fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
      fi
      exit 1
   fi

   local failmsg

   failmsg="failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"

      # shellcheck source=../mulle-bashfunctions/src/mulle-logging.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-logging.sh"
      # shellcheck source=../mulle-bashfunctions/src/mulle-exekutor.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-exekutor.sh" || fail "${failmsg}"
      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-string.sh"   || fail "${failmsg}"
      # shellcheck source=../mulle-bashfunctions/src/mulle-options.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-options.sh"  || fail "${failmsg}"


   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   trap trap_fail INT
   set -o pipefail
}


print_arguments()
{
   while [ $# -ne 0 ]
   do
      echo "$1"
      shift
   done
}


main()
{

   if [ $# -eq 2 -a "$1" == "--args" ]
   then
      local filename

      filename="$2"
      case "${filename}" in
         ""|"-")
            filename=""
         ;;

         *)
            [ -f "${filename}" ] || fail "file \"${filename}\" not found"
         ;;
      esac

      cat "${filename}" | _main
   else
      print_arguments "$@" | _main
   fi
}

#
# leading backslash ? looks like we're getting called from
# mingw via a .BAT or so
#
case "$PATH" in
   '\\'*)
      PATH="${PATH//\\/\/}"
   ;;
esac


_init "$@" # needs params
main "$@"
