#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x


TEST_DIR="`dirname "$0"`"
PROJECT_DIR="$( cd "${TEST_DIR}/.." ; pwd -P)"

PATH="${PROJECT_DIR}:$PATH"
export PATH


main()
{
   _options_mini_main "$@"

   MULLE_MAKE="`which mulle-make`" || exit 1

   local i

   log_verbose "mulle-make: `mulle-make version` (`mulle-make library-path`)"

   for i in "${TEST_DIR}"/*
   do
      if [ -x "$i/run-test" ]
      then
         case "$i" in
            *-xcodebuild)
               if [ "${MULLE_UNAME}" != darwin ]
               then
                  continue
               fi
            ;;
         esac

         log_verbose "------------------------------------------"
         log_info    "$i:"
         log_verbose "------------------------------------------"
         if [ "${MULLE_FLAG_LOG_TERSE}" = "YES" ]
         then
            ( cd "$i" && ./run-test "$@" > /dev/null 2>&1 ) || fail "Test \"$i\" failed"
         else
            ( cd "$i" && ./run-test "$@" ) || fail "Test \"$i\" failed"
         fi
      fi
   done
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
}

init "$@"
main "$@"

