#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_make()
{
   log_fluff "####################################"
   log_fluff ${MULLE_MAKE} ${MULLE_MAKE_FLAGS} "$@" --no-ninja
   log_fluff "####################################"

   exekutor ${MULLE_MAKE} ${MULLE_MAKE_FLAGS} "$@" --no-ninja
}


expect_content()
{
   local output="$1"
   local expect="$2"

   if [ ! -f "${output}" ]
   then
      if [ -z "${expect}" ]
      then
         return
      fi
      fail "Did not produce \"${output}\" as expected"
   else
      if [ -z "${expect}" ]
      then
         fail "Did produce \"${output}\" unexpectedly. Nothing was expected"
      fi
   fi

   if [ -f "${expect}.${MULLE_UNAME}" ]
   then
      expect="${expect}.${MULLE_UNAME}"
   fi

   if [ ! -f "${expect}" ]
   then
      internal_fail "\"${expect}\" is missing from test"
   fi

   local diffs

   diffs="`diff -b "${output}" "${expect}"`"
   if [ $? -ne 0 ]
   then
      # fix for mingw
      if [ `wc -l <<< "${diffs}"` -eq 2 ]
      then
         if egrep -q 'CMAKE_LINKER:PATH=' <<< "${diffs}"
         then
            return 0
         fi
      fi

      log_error "Unexpected output generated"
      cat <<EOF >&2
----------------
Output: ($output)
----------------
`cat "${output}"`
----------------
Expected: ($expect)
----------------
`cat "${expect}"`
----------------
Diff:
----------------
${diffs}
----------------
EOF
      exit 1
   fi
}


run_test()
{
   local directory="$1"; shift
   local xcodebuild_expect="$1"; shift

   #
   # MOCK_TEST_DIR is passed to mock-xcodebuild so it can create
   # paths that look the same
   #
   MOCK_TEST_DIR="${directory}" \
   XCODEBUILD_REDIRECT_FILE="${directory}/xcodebuild-args.txt" \
      run_mulle_make ${MULLE_MAKE_FLAGS} \
               make \
                  --build-dir "${directory}/build" \
                  -DXCODEBUILD="${PWD}/../mock-xcodebuild" \
                  "$@"

   if [ "$?" -ne 0 ]
   then
      exit 1
   fi

   expect_content "${directory}/xcodebuild-args.txt" "${xcodebuild_expect}"

   remove_file_if_present "${directory}/xcodebuild-args.txt"
   rmdir_safer "${directory}/build"
}


main()
{
   MULLE_MAKE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   if [ -z "`command -v "xcodebuild"`" ]
   then
      log_info "xcodebuild not installed, so skipping this test"
      return
   fi

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"

   #
   # Default is release
   #
   run_test "${directory}" "release_xcodebuild.txt" -c "Release"
   log_verbose "----- #1 PASSED -----"

   run_test "${directory}" "debug_xcodebuild.txt" -c "Debug"
   log_verbose "----- #2 PASSED -----"

   run_test "${directory}" "prefix_xcodebuild.txt" -c "Release" --prefix "/tmp"
   log_verbose "----- #3 PASSED -----"

   run_test "${directory}" "sdk_xcodebuild.txt" -c "Release" -s "mulle-sdk"
   log_verbose "----- #4 PASSED -----"

   run_test "${directory}" "user_xcodebuild.txt" -c "Release" -DUSER_INFO="VfL Bochum 1848"
   log_verbose "----- #5 PASSED -----"

   run_test "${directory}" "userplus_xcodebuild.txt" -c "Release" -DUSER_INFO+="VfL Bochum 1848"
   log_verbose "----- #6 PASSED -----"

   run_test "${directory}" "xcconfig_xcodebuild.txt" -c "Release" \
                                                     --xcode-config-file whatever.xcconfig
   log_verbose "----- #7 PASSED -----"

   run_test "${directory}" "paths_xcodebuild.txt" -c "Release" \
                                                  -I /usr/local/include:/usr/include \
                                                  -L /usr/local/lib:/usr/lib \
                                                  -F /Network/Library/Frameworks:/Library/Frameworks
   log_verbose "----- #8 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_MAKE="${MULLE_MAKE:-${PWD}/../../mulle-make}"
}



init "$@"
main "$@"

