#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x


run_mulle_make()
{
   log_fluff "####################################"
   log_fluff ${MULLE_MAKE} ${MULLE_MAKE_FLAGS} "$@" --no-ninja
   log_fluff "####################################"

   exekutor ${MULLE_MAKE} ${MULLE_MAKE_FLAGS} "$@" --no-ninja
}


expect_content()
{
   local output="$1"
   local expect="$2"

   if [ ! -f "${output}" ]
   then
      if [ -z "${expect}" ]
      then
         return
      fi
      fail "Did not produce \"${output}\" as expected"
   else
      if [ -z "${expect}" ]
      then
         fail "Did produce \"${output}\" unexpectedly. Nothing was expected"
      fi
   fi

   if [ -f "${expect}.${MULLE_UNAME}" ]
   then
      expect="${expect}.${MULLE_UNAME}"
   fi
   log_fluff "Using \"${expect}\""

   if [ ! -f "${expect}" ]
   then
      internal_fail "\"${expect}\" is missing from test"
   fi

   local diffs

   diffs="`diff -b "${output}" "${expect}"`"
   if [ $? -ne 0 ]
   then
      # fix for mingw
      if [ `wc -l <<< "${diffs}"` -eq 2 ]
      then
         if egrep -q 'CMAKE_LINKER:PATH=' <<< "${diffs}"
         then
            return 0
         fi
      fi

      if [ "${MULLE_UNAME}" = darwin ]
      then
         if [ -z "`egrep -v -e '-isysroot' <<< "${diffs}"`" ]
         then
            return 0
         fi
      fi

      log_error "Unexpected output generated"
      cat <<EOF >&2
----------------
Output: ($output)
----------------
`cat "${output}"`
----------------
Expected: ($expect)
----------------
`cat "${expect}"`
----------------
Diff:
----------------
${diffs}
----------------
EOF
      exit 1
   fi
}


run_test()
{
   local directory="$1"; shift
   local cmake_expect="$1"; shift
   local make_expect="$1"; shift

   MULLE_TMP_DIR="${directory}" \
   MULLE_TEST_DIR="${PWD}" \
   CMAKE_REDIRECT_FILE="${directory}/cmake-args.txt" \
   MAKE_REDIRECT_FILE="${directory}/make-args.txt" \
      run_mulle_make ${MULLE_MAKE_FLAGS} project --build-dir "${directory}/build" \
                          -DCMAKE="${PWD}/../mock-cmake" \
                          -DMAKE="${PWD}/../mock-make" \
                          "$@"

   if [ "$?" -ne 0 ]
   then
      exit 1
   fi

   expect_content "${directory}/cmake-args.txt" "${cmake_expect}"
   expect_content "${directory}/make-args.txt" "${make_expect}"

   remove_file_if_present "${directory}/cmake-args.txt"
   remove_file_if_present "${directory}/make-args.txt"
   rmdir_safer "${directory}/build"
}


main()
{
   MULLE_MAKE_FLAGS="$@"

   _options_mini_main "$@" && set -x

   local directory

   r_make_tmp_directory || exit 1
   directory="${RVAL}"

   #
   # Default is release
   #
   run_test	"${directory}" "release_cmake.txt" "make.txt"
   log_verbose "----- #1 PASSED -----"
   run_test	"${directory}" "release_cmake.txt" "make.txt" -c Release
   log_verbose "----- #2 PASSED -----"
   run_test	"${directory}" "release_cmake.txt" "make.txt" --release
   log_verbose "----- #3 PASSED -----"

   run_test	"${directory}" "debug_cmake.txt" "make.txt" -c Debug
   log_verbose "----- #4 PASSED -----"
   run_test	"${directory}" "debug_cmake.txt" "make.txt" --debug
   log_verbose "----- #5 PASSED -----"

   run_test	"${directory}" "xxx_cmake.txt" "make.txt" -DXXX=yyy -DASTRING='"a string"' -DOTHER_CFLAGS='-DSTRING=\"string\" -Ipath/with\ space'
   log_verbose "----- #6 PASSED -----"

   # check that known flags are filtered
   run_test	"${directory}" "release_cmake.txt" "make.txt" -DMAKETARGET=filtered_away
   log_verbose "----- #7 PASSED -----"

   run_test "${directory}" "release_cmake.txt" "make.txt"
   log_verbose "----- #8 PASSED -----"

   #
   # check -I -L -F
   #
   run_test	"${directory}" "paths_cmake.txt" "make.txt" -I /usr/local/include:/usr/include \
                                         -L /usr/local/lib:/usr/lib \
                                         -F /Network/Library/Frameworks:/Library/Frameworks
   log_verbose "----- #8 PASSED -----"

   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_MAKE="${MULLE_MAKE:-${PWD}/../../mulle-make}"
}



init "$@"
main "$@"

