#! /usr/bin/env bash

[ "${TRACE}" = "YES" ] && set -x


run_mulle_make()
{
   log_fluff "####################################"
   log_fluff ${MULLE_MAKE} ${MULLE_MAKE_FLAGS} "$@"
   log_fluff "####################################"

   exekutor ${MULLE_MAKE} ${MULLE_MAKE_FLAGS} "$@"
}


expect_content()
{
   local output="$1"
   local expect="$2"

   if [ ! -f "${output}" ]
   then
      if [ -z "${expect}" ]
      then
         return
      fi
      fail "Did not produce \"${output}\" as expected"
   else
      if [ -z "${expect}" ]
      then
         fail "Did produce \"${output}\" unexpectedly. Nothing was expected"
      fi
   fi

   if [ -f "${expect}.${UNAME}" ]
   then
      expect="${expect}.${UNAME}"
   fi

   if [ ! -f "${expect}" ]
   then
      internal_fail "\"${expect}\" is missing from test"
   fi

   local diffs

   diffs="`diff -B "${output}" "${expect}"`"
   if [ $? -ne 0 ]
   then
      log_error "Unexpected output generated"
      cat <<EOF >&2
----------------
Output: ($output)
----------------
`cat "${output}"`
----------------
Expected: ($expect)
----------------
`cat "${expect}"`
----------------
Diff:
----------------
${diffs}
----------------
EOF
      exit 1
   fi
}


run_test()
{
   local meson_expect="$1"; shift
   local make_expect="$1"; shift

   local meson_output
   local make_output

   meson_output="${directory}/meson-args.txt"
   make_output="${directory}/make-args.txt"

   MESON_REDIRECT_FILE="${meson_output}" \
   NINJA_REDIRECT_FILE="${make_output}" \
      run_mulle_make make --build-dir "${directory}/build" \
                          -DMESON="${PWD}/../mock-meson" \
                          -DNINJA="${PWD}/../mock-ninja" \
                          "$@"

   if [ "$?" -ne 0 ]
   then
      exit 1
   fi

   expect_content "${meson_output}" "${meson_expect}"
   expect_content "${make_output}" "${make_expect}"

   remove_file_if_present "${meson_output}"
   remove_file_if_present "${make_output}"

   rmdir_safer "${directory}/build"
}


main()
{
   MULLE_MAKE_FLAGS="$@"

   _options_mini_main "$@"

   local directory

   directory="`make_tmp_directory`" || exit 1
   directory="${directory:-/tmp/build}"

   #
   # Default is release
   #
   run_test "release_meson.txt" "ninja.txt" --no-determine-xcode-sdk
   log_verbose "----- #1 PASSED -----"

   run_test "release_prefix_meson.txt" "ninja.txt" --no-determine-xcode-sdk "--prefix" "/tmp/foo"
   log_verbose "----- #2 PASSED -----"

   #
   # check -I -L -F
   #
   run_test "paths_meson.txt" "ninja.txt" -DDETERMINE_XCODE_SDK="NO" \
                                             -I /usr/local/include:/usr/include \
                                             -L /usr/local/lib:/usr/lib \
                                             -F /Network/Library/Frameworks:/Library/Frameworks
   log_verbose "----- #3 PASSED -----"


   log_info "----- ALL PASSED -----"

   rmdir_safer "${directory}"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env library-path`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_MAKE="${MULLE_MAKE:-${PWD}/../../mulle-make}"
}



init "$@"
main "$@"

